name: Laravel

on:
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      # with:
        # php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Create Zip Deployment packeage 
    # Navigate to Laravel directory
      # run: cd api
      run: zip -r deploy.zip
    # - name: Copy .env
    - name : Deploy to Beenstalk
    run : einaregilsson/beanstalk-deploy@v21
      # run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    # - name: List directory contents
      # run: ls -la
    # - name: Navigate to Laravel directory
      # run: cd api/
    # - name: List directory contents
      # run: ls -la
    # - name: Install Dependencies
      # run: composer install
      # run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # - name: Generate key
      # run: php artisan key:generate
    # - name: Directory Permissions
      # run: chmod -R 777 storage bootstrap/cache
    # - name: Create Database
      # run: |
        # mysql -h localhost -u root --password=root -e "CREATE DATABASE laravel_test;"
        # php artisan migrate --seed --env=testing
    # - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      # env:
        # DB_CONNECTION: mysql
        # DB_HOST: localhost
        # DB_PORT: 3306
        # DB_DATABASE: laravel_test
        # DB_USERNAME: root
        # DB_PASSWORD: root
      # run: php artisan test

      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: larav
        environment_name: larav-env
        existing_buket_name: elasticbeanstalk-eu-west-1-851725478663
        version_label: 12345
        region: eu-west-1
        deployment_package: deploy.zip
# 
