name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install PHP (optional)
      # Uncomment if you need a specific version
      # uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - name: Navigate to Laravel directory (optional)
      # Uncomment if needed
      run: cd api
    - name: Create Zip Deployment Package
      run: zip -r deploy.zip .  # Include everything in the current directory
    - name: Copy .env (optional)
      # Uncomment if your application relies on it
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Deploy to Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: larav
        environment_name: larav-env
        existing_buket_name: elasticbeanstalk-eu-west-1-851725478663
        version_label: 12345
        region: eu-west-1
        deployment_package: deploy.zip
